### ISSUE TITLE
can't connect between jenkin master and jenkin slave 

### ISSUE THREAD

**Issue by MatthewLiHW** [rasselin/os-ext-testing#16]
Hi, 

    I have set up an third party CI system according to your guide, however, I meet an error, shown as

   [04/13/15 07:24:14] [SSH] Opening SSH connection to 192.168.120.14:22.
ERROR: Server rejected the 1 private key(s) for jenkins (credentialId:75c5348f-3200-4b1b-9e4e-7af2fe6a9445/method:publickey)
[04/13/15 07:24:14] [SSH] Authentication failed.
hudson.AbortException: Authentication failed.
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1178)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:701)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:696)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[04/13/15 07:24:14] Launch failed - cleaning up connection
[04/13/15 07:24:14] [SSH] Connection closed.

I also set up an third party CI according to jaypipes's guide, nodepool isn't included in his scripts, so my idea is that if I should write nodepool pramaters in install_slave.sh to set  credential_Id in jenkins slave?

**Comment by rasselin** [comment]
First, if possible, try getting it to work with security disabled. I succeeded recently, but it was not as straight-forward as it was the first time I did it. I think there were some changes in Jenkins. So I don't have a good recipe. You do need to get everything in sync. 
        export JENKINS_API_KEY=
        export JENKINS_CREDENTIALS_ID=
API key you get from the UI.
Credentials_ID you get from /var/lib/jenkins/credentials.xml

When you use nodepool, install_slave.sh is not used at all. That script is used to setup a static jenkins slave. Instead, nodepool creates single-use jenkins slaves and runs the scripts it is configured with (https://github.com/rasselin/os-ext-testing-data/blob/master/etc/nodepool/nodepool.yaml.erb.sample#L1, https://github.com/rasselin/os-ext-testing-data/blob/master/etc/nodepool/nodepool.yaml.erb.sample#L47) .  
Alternatively, you can also use Disk Image Builder (I highly recommend that approach). In both cases, these are where the scripts are pulled from (in addition to custom scripts you put in your -data repo):
https://github.com/openstack-infra/project-config/tree/master/nodepool/elements
https://github.com/openstack-infra/project-config/tree/master/nodepool/scripts

DIB sample is available here:
https://github.com/openstack-infra/system-config/blob/master/modules/openstack_project/templates/nodepool/nodepool.yaml.erb#L2
Documentation is here: http://ci.openstack.org/nodepool/configuration.html

**Comment by MatthewLiHW** [comment]
thanks a lot. I give up the static jenkins slave installation.
my JENKINS_API_KEY/JENKINS_CREDENTIALS_ID are correct configured.
now, I have four machines, one (IP1 )runs the jenkins install_master.sh, the other 3(IP2,IP3,IP4) are setup by openstack with one controller+2compute, my idea is to use these 3 as the test cloud, I have search the scripts under /etc/nodepool, my idea is add the hostname after  https://github.com/rasselin/os-ext-testing-data/blob/master/etc/nodepool/nodepool.yaml.erb.sample#L47 with prepare_node_devstack.sh, now, I am a fresh man at this, how do you think about this idea? or do you have other suggestions to connect the 3 hosts as the nodepool test cloud?

**Comment by rasselin** [comment]
You would put the auth url for the test cloud (your 'provider' of instances) here:
https://github.com/rasselin/os-ext-testing-data/blob/master/etc/nodepool/nodepool.yaml.erb.sample#L34
as explained here:
http://ci.openstack.org/nodepool/configuration.html#providers
