### ISSUE TITLE
puppet template miss

### ISSUE THREAD

**Issue by MatthewLiHW** [rasselin/os-ext-testing#18]
hi, I have installed the log server by using the install_log_server.sh, however, it fails to find logs-dev.vhost.erb and logs.vhost.erb under https://github.com/openstack-infra/system-config/tree/master/modules/openstack_project/templates, and I find one example in https://github.com/testing-cabal/ci-config/tree/master/modules/openstack_project/templates, I don't know if is it need to put a patch to the openstack-infra/system-config to add these two erb files?

**Comment by rasselin** [comment]
There's been a lot of refactoring going on. I think your fork/clone is a bit behind master. Which version of install_log_server.sh are you using? You should be using the latest one: https://github.com/rasselin/os-ext-testing/blob/master/puppet/install_log_server.sh

This pulls in the common-log server from here: https://github.com/openstack-infra/puppet-openstackci/blob/master/manifests/logserver.pp

Which uses these .erb templates: https://github.com/openstack-infra/puppet-openstackci/blob/master/templates/logs.vhost.erb

These are no longer hosted in system-config.

This refactoring is being done as part of: http://specs.openstack.org/openstack-infra/infra-specs/specs/openstackci.html

You should expect quite a few changes in the near future (i.e. this week) as we migrate over to this new solution. I'm including upgrade/migration instructions in the README.md.

**Comment by MatthewLiHW** [comment]
I missed the README contents for install_log_server.sh, after I added the erb file, it succeed. 
yep, I should update my repo along with yours.
It will be very nice for you to do some changes, maybe in README part, you can add sth for how to use the log server.

**Comment by rasselin** [comment]
sth? if you can update the readme and submit a pull request that would be best.

**Comment by MatthewLiHW** [comment]
hi, I mean after I setup the LAMP environment and the log server, how the  jenkins user will be able to upload files to /srv/static/logs? is it automate?

**Comment by rasselin** [comment]
Hi, I don't know what is a LAMP environment. 

Regarding the log server, it just sets up the jenkins user with public key set in the authorized keys. 
https://github.com/rasselin/os-ext-testing/blob/master/puppet/install_log_server.sh#L11

For the jenkins user to upload log files, you need to use a publisher such as: https://github.com/rasselin/os-ext-testing/blob/master/puppet/modules/os_ext_testing/templates/jenkins_job_builder/config/macros.yaml.erb#L116

**Comment by rasselin** [comment]
Closing. Please re-open if you still have issues.
