### ISSUE TITLE
How to use the log server ?

### ISSUE THREAD

**Issue by tang-chen** [rasselin/os-ext-testing#19]
I run the install_log_server.sh and it completed. I set the DOMAIN to localhost, which means I want to set the log server on my Jenkins Master, I think. And after that, how can I use the log server ? How could Jenkins upload logs to the server automatically ?

Thanks.

**Comment by rasselin** [comment]
Seems you found your answer. Use a publisher. e.g. https://github.com/rasselin/os-ext-testing-data/blob/master/etc/jenkins_jobs/config/dsvm-cinder-driver.yaml.sample#L73
