### ISSUE TITLE
Puppet dependencies error while setting up the Jenkins Master.

### ISSUE THREAD

**Issue by beckmani** [rasselin/os-ext-testing#8]
puppet module dependencies cause errors when running the following commands:

wget https://raw.github.com/rasselin/os-ext-testing/master/puppet/install_master.sh
bash install_master.sh

**Comment by rasselin** [comment]
Please include the error messages. Note that as stated in the README ubuntu 14.04 is not yet supported. You should use ubuntu 12.04.

**Comment by rasselin** [comment]
BTW, if you 'need' to use 14.04, there's a WIP patch here you can use. With this you should be able to install the dependencies, but not fully tested. Hopefully will get that done by end of next week.
https://review.openstack.org/#/c/141518/

**Comment by rasselin** [comment]
https://review.openstack.org/#/c/141518/ merged & didn't hear any updates, so closing.
If there's still an issue, let me know. Thanks!
